# Generated by Django 5.2.3 on 2025-06-17 01:34

import recipe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('cooking_time', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_images/')),
                ('cover_images', models.ImageField(blank=True, default=recipe.models.cover_image, null=True, upload_to='recipe_covers/')),
            ],
        ),
    ]
