# Generated by Django 5.2.3 on 2025-06-15 23:40

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_album_title_alter_artist_debut_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='album_images/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(validators=[core.models.validate_release_date]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
